Show evaluation time in the evaluations overview
NixOS/hydra pull request #887
Opened 2021-03-09 17:28 UTC by dasJ

![image](https://user-images.githubusercontent.com/4971975/110512081-2e81a500-8105-11eb-8a2c-341094312e21.png)

2021-04-12 17:20 UTC, grahamc requested changes
Looks pretty good! I think the function should probably live somewhere else, to prevent confusion if someone tries to use it elsewhere. I'm not totally sure if this is the best answer, but I'd be happy enough with it.

2021-04-12 17:20 UTC, grahamc commented on src/lib/Hydra/Controller/Jobset.pm
> +
I think this should probably move to TT.pm:

```diff
--- a/src/lib/Hydra/View/TT.pm
+++ b/src/lib/Hydra/View/TT.pm
@@ -9,7 +9,7 @@ __PACKAGE__->config(
     ENCODING => 'utf-8',
     PRE_CHOMP => 1,
     POST_CHOMP => 1,
-    expose_methods => [qw/buildLogExists buildStepLogExists jobExists stripSSHUser/]);
+    expose_methods => [qw/buildLogExists buildStepLogExists jobExists stripSSHUser relativeDuration/]);
 
 sub buildLogExists {
     my ($self, $c, $build) = @_;
@@ -34,6 +34,11 @@ sub stripSSHUser {
     }
 }
 
+sub relativeDuration {
+    my ($self, $c, $seconds) = @_;
+    return Time::Seconds->new($seconds)->pretty();
+}
+
```

2021-06-29 14:38 UTC, grahamc commented
I applied my change over in https://github.com/NixOS/hydra/compare/master...DeterminateSystems:pr-887-review  -- I propose we squash these commits if you're up for it.

2021-06-29 14:53 UTC, dasJ commented
Like this?

2021-06-29 14:54 UTC, grahamc approved these changes
lgtm, thanks! just waiting for CI to be green

2021-06-29 14:59 UTC, merged